spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cash_card
    username: root
    password: '@+Amb3r4now2023'
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect 
